name: counter-strike
image: ubuntu-16-04-x64
config:
  #cloud-config
  packages:
    - git
  runcmd:
    - set -eo pipefail
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git clone --depth=1 https://github.com/vitordino/counter-strike-docker.git
    - sudo apt-get -y update
    - sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo apt-key fingerprint 0EBFCD88
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get -y update
    - sudo apt-get -y install docker-ce
    - sudo systemctl enable docker
    - sudo systemctl restart docker
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - cd ./counter-strike-docker
    - cp example.env .env
    - docker-compose build
    - docker-compose up -d server
